// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  api: create.doc("api", {"index.mdx": () => import("../content/api-reference/index.mdx?collection=api"), "api-keys/createApiKey.mdx": () => import("../content/api-reference/api-keys/createApiKey.mdx?collection=api"), "api-keys/deleteApiKey.mdx": () => import("../content/api-reference/api-keys/deleteApiKey.mdx?collection=api"), "api-keys/getAllApiKeys.mdx": () => import("../content/api-reference/api-keys/getAllApiKeys.mdx?collection=api"), "api-keys/overview.mdx": () => import("../content/api-reference/api-keys/overview.mdx?collection=api"), "api-keys/revokeApiKey.mdx": () => import("../content/api-reference/api-keys/revokeApiKey.mdx?collection=api"), "api-keys/rotateApiKey.mdx": () => import("../content/api-reference/api-keys/rotateApiKey.mdx?collection=api"), "authentication/getSession.mdx": () => import("../content/api-reference/authentication/getSession.mdx?collection=api"), "authentication/overview.mdx": () => import("../content/api-reference/authentication/overview.mdx?collection=api"), "authentication/sendOTP.mdx": () => import("../content/api-reference/authentication/sendOTP.mdx?collection=api"), "authentication/signOut.mdx": () => import("../content/api-reference/authentication/signOut.mdx?collection=api"), "authentication/verifyOTP.mdx": () => import("../content/api-reference/authentication/verifyOTP.mdx?collection=api"), "github/getGitHubIssues.mdx": () => import("../content/api-reference/github/getGitHubIssues.mdx?collection=api"), "github/getGitHubStats.mdx": () => import("../content/api-reference/github/getGitHubStats.mdx?collection=api"), "github/overview.mdx": () => import("../content/api-reference/github/overview.mdx?collection=api"), "github/syncGitHubStats.mdx": () => import("../content/api-reference/github/syncGitHubStats.mdx?collection=api"), "health/healthCheck.mdx": () => import("../content/api-reference/health/healthCheck.mdx?collection=api"), "health/overview.mdx": () => import("../content/api-reference/health/overview.mdx?collection=api"), "roadmap/getRoadmap.mdx": () => import("../content/api-reference/roadmap/getRoadmap.mdx?collection=api"), "roadmap/getRoadmapFeatureById.mdx": () => import("../content/api-reference/roadmap/getRoadmapFeatureById.mdx?collection=api"), "roadmap/getRoadmapStats.mdx": () => import("../content/api-reference/roadmap/getRoadmapStats.mdx?collection=api"), "roadmap/overview.mdx": () => import("../content/api-reference/roadmap/overview.mdx?collection=api"), "users/getCurrentUser.mdx": () => import("../content/api-reference/users/getCurrentUser.mdx?collection=api"), "users/overview.mdx": () => import("../content/api-reference/users/overview.mdx?collection=api"), "users/updateUserName.mdx": () => import("../content/api-reference/users/updateUserName.mdx?collection=api"), }),
  docs: create.doc("docs", {"api-keys.mdx": () => import("../content/docs/api-keys.mdx?collection=docs"), "documentation.mdx": () => import("../content/docs/documentation.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "overview.mdx": () => import("../content/docs/overview.mdx?collection=docs"), "architecture/auth-system.mdx": () => import("../content/docs/architecture/auth-system.mdx?collection=docs"), "architecture/database-schema.mdx": () => import("../content/docs/architecture/database-schema.mdx?collection=docs"), "architecture/monorepo.mdx": () => import("../content/docs/architecture/monorepo.mdx?collection=docs"), "architecture/pdf-generation.mdx": () => import("../content/docs/architecture/pdf-generation.mdx?collection=docs"), "architecture/state-management.mdx": () => import("../content/docs/architecture/state-management.mdx?collection=docs"), "contributing/coding-standards.mdx": () => import("../content/docs/contributing/coding-standards.mdx?collection=docs"), "contributing/index.mdx": () => import("../content/docs/contributing/index.mdx?collection=docs"), "getting-started/docker-deployment.mdx": () => import("../content/docs/getting-started/docker-deployment.mdx?collection=docs"), "getting-started/local-setup.mdx": () => import("../content/docs/getting-started/local-setup.mdx?collection=docs"), "getting-started/migration-v2.mdx": () => import("../content/docs/getting-started/migration-v2.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "legal/license.mdx": () => import("../content/docs/legal/license.mdx?collection=docs"), "legal/privacy-policy.mdx": () => import("../content/docs/legal/privacy-policy.mdx?collection=docs"), "legal/security.mdx": () => import("../content/docs/legal/security.mdx?collection=docs"), "legal/terms-of-service.mdx": () => import("../content/docs/legal/terms-of-service.mdx?collection=docs"), "operations/api-key-security-runbook.mdx": () => import("../content/docs/operations/api-key-security-runbook.mdx?collection=docs"), "operations/environment-variables.mdx": () => import("../content/docs/operations/environment-variables.mdx?collection=docs"), "operations/service-status.mdx": () => import("../content/docs/operations/service-status.mdx?collection=docs"), "user-guides/account-management.mdx": () => import("../content/docs/user-guides/account-management.mdx?collection=docs"), "user-guides/creating-your-first-resume.mdx": () => import("../content/docs/user-guides/creating-your-first-resume.mdx?collection=docs"), "user-guides/exporting-and-sharing.mdx": () => import("../content/docs/user-guides/exporting-and-sharing.mdx?collection=docs"), "user-guides/resume-templates.mdx": () => import("../content/docs/user-guides/resume-templates.mdx?collection=docs"), }),
};
export default browserCollections;