// @ts-nocheck
import * as __fd_glob_58 from "../content/docs/user-guides/resume-templates.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/user-guides/exporting-and-sharing.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/user-guides/creating-your-first-resume.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/user-guides/account-management.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/operations/service-status.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/operations/environment-variables.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/operations/api-key-security-runbook.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/legal/terms-of-service.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/legal/security.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/legal/privacy-policy.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/legal/license.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/getting-started/quick-start.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/getting-started/migration-v2.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/getting-started/local-setup.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/getting-started/docker-deployment.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/contributing/index.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/contributing/coding-standards.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/architecture/state-management.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/architecture/pdf-generation.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/architecture/monorepo.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/architecture/database-schema.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/architecture/auth-system.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/overview.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/documentation.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/api-keys.mdx?collection=docs"
import { default as __fd_glob_32 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_31 from "../content/api-reference/users/updateUserName.mdx?collection=api"
import * as __fd_glob_30 from "../content/api-reference/users/overview.mdx?collection=api"
import * as __fd_glob_29 from "../content/api-reference/users/getCurrentUser.mdx?collection=api"
import * as __fd_glob_28 from "../content/api-reference/roadmap/overview.mdx?collection=api"
import * as __fd_glob_27 from "../content/api-reference/roadmap/getRoadmapStats.mdx?collection=api"
import * as __fd_glob_26 from "../content/api-reference/roadmap/getRoadmapFeatureById.mdx?collection=api"
import * as __fd_glob_25 from "../content/api-reference/roadmap/getRoadmap.mdx?collection=api"
import * as __fd_glob_24 from "../content/api-reference/health/overview.mdx?collection=api"
import * as __fd_glob_23 from "../content/api-reference/health/healthCheck.mdx?collection=api"
import * as __fd_glob_22 from "../content/api-reference/authentication/verifyOTP.mdx?collection=api"
import * as __fd_glob_21 from "../content/api-reference/authentication/signOut.mdx?collection=api"
import * as __fd_glob_20 from "../content/api-reference/authentication/sendOTP.mdx?collection=api"
import * as __fd_glob_19 from "../content/api-reference/authentication/overview.mdx?collection=api"
import * as __fd_glob_18 from "../content/api-reference/authentication/getSession.mdx?collection=api"
import * as __fd_glob_17 from "../content/api-reference/github/syncGitHubStats.mdx?collection=api"
import * as __fd_glob_16 from "../content/api-reference/github/overview.mdx?collection=api"
import * as __fd_glob_15 from "../content/api-reference/github/getGitHubStats.mdx?collection=api"
import * as __fd_glob_14 from "../content/api-reference/github/getGitHubIssues.mdx?collection=api"
import * as __fd_glob_13 from "../content/api-reference/api-keys/rotateApiKey.mdx?collection=api"
import * as __fd_glob_12 from "../content/api-reference/api-keys/revokeApiKey.mdx?collection=api"
import * as __fd_glob_11 from "../content/api-reference/api-keys/overview.mdx?collection=api"
import * as __fd_glob_10 from "../content/api-reference/api-keys/getAllApiKeys.mdx?collection=api"
import * as __fd_glob_9 from "../content/api-reference/api-keys/deleteApiKey.mdx?collection=api"
import * as __fd_glob_8 from "../content/api-reference/api-keys/createApiKey.mdx?collection=api"
import * as __fd_glob_7 from "../content/api-reference/index.mdx?collection=api"
import { default as __fd_glob_6 } from "../content/api-reference/users/meta.json?collection=api"
import { default as __fd_glob_5 } from "../content/api-reference/roadmap/meta.json?collection=api"
import { default as __fd_glob_4 } from "../content/api-reference/github/meta.json?collection=api"
import { default as __fd_glob_3 } from "../content/api-reference/health/meta.json?collection=api"
import { default as __fd_glob_2 } from "../content/api-reference/authentication/meta.json?collection=api"
import { default as __fd_glob_1 } from "../content/api-reference/api-keys/meta.json?collection=api"
import { default as __fd_glob_0 } from "../content/api-reference/meta.json?collection=api"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const api = await create.docs("api", "content/api-reference", {"meta.json": __fd_glob_0, "api-keys/meta.json": __fd_glob_1, "authentication/meta.json": __fd_glob_2, "health/meta.json": __fd_glob_3, "github/meta.json": __fd_glob_4, "roadmap/meta.json": __fd_glob_5, "users/meta.json": __fd_glob_6, }, {"index.mdx": __fd_glob_7, "api-keys/createApiKey.mdx": __fd_glob_8, "api-keys/deleteApiKey.mdx": __fd_glob_9, "api-keys/getAllApiKeys.mdx": __fd_glob_10, "api-keys/overview.mdx": __fd_glob_11, "api-keys/revokeApiKey.mdx": __fd_glob_12, "api-keys/rotateApiKey.mdx": __fd_glob_13, "github/getGitHubIssues.mdx": __fd_glob_14, "github/getGitHubStats.mdx": __fd_glob_15, "github/overview.mdx": __fd_glob_16, "github/syncGitHubStats.mdx": __fd_glob_17, "authentication/getSession.mdx": __fd_glob_18, "authentication/overview.mdx": __fd_glob_19, "authentication/sendOTP.mdx": __fd_glob_20, "authentication/signOut.mdx": __fd_glob_21, "authentication/verifyOTP.mdx": __fd_glob_22, "health/healthCheck.mdx": __fd_glob_23, "health/overview.mdx": __fd_glob_24, "roadmap/getRoadmap.mdx": __fd_glob_25, "roadmap/getRoadmapFeatureById.mdx": __fd_glob_26, "roadmap/getRoadmapStats.mdx": __fd_glob_27, "roadmap/overview.mdx": __fd_glob_28, "users/getCurrentUser.mdx": __fd_glob_29, "users/overview.mdx": __fd_glob_30, "users/updateUserName.mdx": __fd_glob_31, });

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_32, }, {"api-keys.mdx": __fd_glob_33, "documentation.mdx": __fd_glob_34, "index.mdx": __fd_glob_35, "overview.mdx": __fd_glob_36, "architecture/auth-system.mdx": __fd_glob_37, "architecture/database-schema.mdx": __fd_glob_38, "architecture/monorepo.mdx": __fd_glob_39, "architecture/pdf-generation.mdx": __fd_glob_40, "architecture/state-management.mdx": __fd_glob_41, "contributing/coding-standards.mdx": __fd_glob_42, "contributing/index.mdx": __fd_glob_43, "getting-started/docker-deployment.mdx": __fd_glob_44, "getting-started/local-setup.mdx": __fd_glob_45, "getting-started/migration-v2.mdx": __fd_glob_46, "getting-started/quick-start.mdx": __fd_glob_47, "legal/license.mdx": __fd_glob_48, "legal/privacy-policy.mdx": __fd_glob_49, "legal/security.mdx": __fd_glob_50, "legal/terms-of-service.mdx": __fd_glob_51, "operations/api-key-security-runbook.mdx": __fd_glob_52, "operations/environment-variables.mdx": __fd_glob_53, "operations/service-status.mdx": __fd_glob_54, "user-guides/account-management.mdx": __fd_glob_55, "user-guides/creating-your-first-resume.mdx": __fd_glob_56, "user-guides/exporting-and-sharing.mdx": __fd_glob_57, "user-guides/resume-templates.mdx": __fd_glob_58, });